Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua
MainGUI.Login = Saioa hasi
MainGUI.Register= Erregistratu
MainGUI.mainTitle=Ez duzu saioa hasi

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak
ShowSaleGUI.Erosi=Erosi
ShowSaleGUI.CantBuyOwnProduct =Ez duzu saioa hasi 
ShowSaleGUI.Saskia= Saskira gehitu
ShowSaleGUI.SaskiaIkusi= Saskia ikusi
ShowSaleGUI.AddedToSaskia= Eskaintza saskira gehitu da
ShowSaleGUI.AddToSaskiaError= Eskaintza dagoeneko saskian dago

DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da

MainGUIErregistratuta.ErositakoProduktuakIkusi = Erositako produktuak ikusi
MainGUIErregistratuta.Mugimenduak = Mugimenduak ikusi
MainGUIErregistratuta.Dirua = Dirua sartu edo atera
MainGUIErregistratuta.SaioaItxi = Saioa itxi
MainGUIErregistratuta.ErreklamazioakIkusi = Erreklamazioak ikusi
MainGUIErregistratuta.EskaerakIkusi = Eskaerak ikusi
MainGUIErregistratuta.BalorazioakIkusi = Balorazioak ikusi
MainGUIErregistratuta.EskaerakEgin = Eskaerak egin
MainGUIErregistratuta.OfertakIkusi = Eskaintzak ikusi



LoginGUI.Email=Posta elektronikoa
LoginGUI.Password=Pasahitza
LoginGUI.Login=Saioa hasi
LoginGUI.ErrorQueary=Posta elektronikoa edo pasahitza okerra da
LoginGUI.Error = Saioa hastean errorea

RegisterGUI.Email= Posta elektronikoa
RegisterGUI.Password= Pasahitza
RegisterGUI.ConfirmPassword=	Pasahitza errepikatu
RegisterGUI.Register=Erregistratu
RegisterGUI.Name=Izena
RegisterGUI.Telephone=	Telefonoa
RegisterGUI.Exit =Irten
RegisterGUI.ErrorPassword=Pasahitzak ez dira berdinak
RegisterGUI.ErrorQueary=Eremu guztiak bete behar dira
RegisterGUI.ErrorEmail=Email hori dagoeneko erregistratuta dago
RegisterGUI.Ondo = Erregistroa ondo burutu da
RegisterGUI.CancelButton=Itxi

BuyProductGUI.kontu = Kontu zenbakia
BuyProductGUI.Error = Kontu zenbakia ez da zuzena
BuyProductGUI.Success = Erosketa ondo burutu da
BuyProductGUI.InsufficientFunds = Kontuan ez dago dirurik nahikorik
BuyProductGUI.AlreadySold = Produktua dagoeneko salduta dago

DiruaSartuAteraGUI.Title= Sartu diru kopuru bat
DiruaSartuAteraGUI.Sartu= Sartu dirua
DiruaSartuAteraGUI.Atera= Atera dirua
DiruaSartuAteraGUI.Itxi= Itxi
DiruaSartuAteraGUI.SartuMessage= Dirua kontuan sartu da 
DiruaSartuAteraGUI.AteraMessage= Dirua kontutik atera da
DiruaSartuAteraGUI.EzDagoDiruKopMessage= Kontuan ez dago diru kopuru hori
DiruaSartuAteraGUI.DiruKop = Diru kopurua

ErositakoProduktuakIkusiGUI.ErreklamazioaIpini= Erreklamazioa ipini
ErositakoProduktuakIkusiGUI.BalorazioaJarri= Balorazioa jarri

ErreklamazioakIpiniGUI.Titulua = Titulua
ErreklamazioakIpiniGUI.Aukeratu = Aukeratu produktuaren arazoaren irudia
ErreklamazioakIpiniGUI.botoiAukeratu = Irudia aukeratu
ErreklamazioakIpiniGUI.erreklamazioaIpini = Erreklamazioa bidali
ErreklamazioakIpiniGUI.itxi = Itxi
ErreklamazioakIpiniGUI.deskripzioa = Deskribapena

MainGUIAdmin.aukera= Aukeratu aukera
MainGUIAdmin.erreklamazioakIkusi= Erreklamazioak ikusi
MainGUIAdmin.logOut= Saioa itxi

OfertaSortuGUI.title=Tituloa
OfertaSortuGUI.description=Deskripzioa
OfertaSortuGUI.price=Prezioa
OfertaSortuGUI.btnSortu=Eskaintza sortu
OfertaSortuGUI.btnClose=Itxi
OfertaSortuGUI.successMessage=Eskaintza ondo sortu da
OfertaSortuGUI.successTitle=Arrakasta
OfertaSortuGUI.errorPrice=Prezioa baliozko zenbaki bat izan behar da
OfertaSortuGUI.errorCreating=Errorea eskaintza sortzean
OfertaSortuGUI.errorTitle=Akatsa

OfertakIkusiGUI.title = Eskaintza xehetasunak
OfertakIkusiGUI.eskaera= Eskaerak
OfertakIkusiGUI.description= Deskripzioa
OfertakIkusiGUI.price= Prezioa
OfertakIkusiGUI.seller= Salmenta egilea
OfertakIkusiGUI.btnClose= Itxi
OfertakIkusiGUI.errorUser= Erabiltzailea ez da aurkitu
OfertakIkusiGUI.error= Eskaintzak kargatzean errorea
OfertakIkusiGUI.noEskaerak= Ez dago eskaerarik
OfertakIkusiGUI.info= Informazioa
OfertakIkusiGUI.noOfertas= Ez daude eskaintzak
OfertakIkusiGUI.errorLoading= Eskaintzak kargatzean errorea
OfertakIkusiGUI.action= Ekintza
OfertakIkusiGUI.btnBuy= Erosi
OfertakIkusiGUI.buyConfirmation= Eskaintza erosi nahi duzula ziur zaude?
OfertakIkusiGUI.buySuccess = Eskaintza ondo erosi da
OfertakIkusiGUI.buyError= Eskaintza erostean errorea


EskaerakEginGUI.send = Bidali eskaera
EskaerakEginGUI.label = Eskaera idatzi
EskaerakEginGUI.error = ERROR, eskaera idatzi behar da
EskaerakEginGUI.success = Eskaera ondo bidali da

ErreklamazioakEbatziGUI.Deuseztatu= Deuseztatu
ErreklamazioakEbatziGUI.Onartu= Onartu

SaskiaGUI.btnAplicarDesc = Deskontua aplikatu
SaskiaGUI.btnComprar = Erosi
SaskiaGUI.btnSaleGehiago = Beste eskaintza batzuk ikusi
SaskiaGUI.prezioTotala = Prezio totala:
SaskiaGUI.delete = Produktua ezabatu




